server:
  port: 8081

spring:
  application:
    name: auth-service

  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    metrics:
      export:
        prometheus:
          enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0

  threads:
    virtual:
      enabled: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 2592000000

app:
  security:
    gateway-auth:
      enabled: true
      header-name: X-Gateway-Authenticated
      expected-value: "true"
      user-id-header: X-User-Id
      public-path-prefixes:
        - /api/v1/auth/send-otp
        - /api/v1/auth/verify
        - /api/v1/auth/refresh
        - /api/v1/auth/oauth
  redis:
    auth:
      otp-prefix: "otp:"
      otp-rate-limit-prefix: "rate_limit:otp:"
      otp-attempts: "otp:attempts:"
      otp-ttl: 5m
      otp-rate-limit-max-requests: 1
      otp-verification-max-attempts: 5
      otp-rate-limit-window: 1m
      session-prefix: "user:"
      session-suffix: ":sessions"

  google:
    client-id: ${GOOGLE_CLIENT_ID}

  kafka:
    topics:
      user-activity: user-activity-events

  outbox:
    scheduler:
      poll-interval: 1000
      batch-size: 50
      batch-processing-time: 5 #seconds
      fixed-delay: 2000 #ms
      cleanup-cron: "0 0 3 * * *"