server:
  port: 8082

spring:
  application:
    name: profile-service

  management:
    tracing:
      enabled: true
      sampling:
        probability: 1.0
    zipkin:
      tracing:
        endpoint: ${ZIPKIN_URL:http://localhost:9411/api/v2/spans}

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/profile_db?authSource=admin
      auto-index-creation: false
    redis:
      host: localhost
      port: 6379

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  security:
    gateway-auth:
      enabled: true
      header-name: X-Gateway-Authenticated
      expected-value: "true"
      user-id-header: X-User-Id
      internal-path-prefix: /api/v1/internal/
  kafka:
    topics:
      user-activity: user-activity-events
      user-presence: user-presence-events

  profile:
    max-photos: 9
    min-age: 18
    default-search-radius-km: 50.0

  media:
    public-prefix: "/media/"

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket-name: tinder-media