server:
  port: 8082

spring:
  application:
    name: profile-service

  data:
    mongodb:
      uri: mongodb://admin:password@localhost:27017/profile_db?authSource=admin
      auto-index-creation: true

  threads:
    virtual:
      enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

app:
  kafka:
    topics:
      user-activity: user-activity-events
      user-presence: user-presence-events

  profile:
    max-photos: 9
    min-age: 18
    default-search-radius-km: 50.0

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket-name: tinder-media